version: "3"

services:
  mumble:
    image: teropietila/lanparty-mumble:1.2.19
    ports:
      - "64738:64738"
    volumes:
      - murmur-data:/var/local/murmur
    networks:
      - lanparty
    environment:
      - ADMIN_PASS


  opendchub:
    image: teropietila/lanparty-opendchub:0.8.3
    ports:
      - "411:411"
      - "53696:53696"
    volumes:
      - opendchub-data:/root/.opendchub
    networks:
      - lanparty
    environment:
      - ADMIN_PASS


networks:
  lanparty:


volumes:
  opendchub-data:
  murmur-data:
